CREATE TABLE MECHANIC(
    MECHNUM INT PRIMARY KEY,
    MECHNAME VARCHAR(30) NOT NULL,
    AGE INT NOT NULL,
    SALARY NUMERIC(9,2) DEFAULT 0.0 NOT NULL,
    AIRNAME VARCHAR(30) NOT NULL,
    FOREIGN KEY (AIRNAME) REFERENCES AIRPORT(AIRNAME) 
);

CREATE TABLE AIRPORT (
    AIRNAME VARCHAR(30) PRIMARY KEY,
    CITY VARCHAR(30) NOT NULL,
    STATE VARCHAR(30) NOT NULL,
    SIZE INT,
    YEAROPENED DATE NOT NULL
);

CREATE TABLE SKILL(
    SKILLNUM INT PRIMARY KEY,
    SKILLNAME VARCHAR(30) NOT NULL,
    SKILLCAT VARCHAR(20) NOT NULL
);

CREATE TABLE QUALIFICATION(
    YEARQUAL DATE NOT NULL,
    PROFRATE INT NOT NULL,
    MECHNUM INT,
    SKILLNUM INT,
    PRIMARY KEY (MECHNUM, SKILLNUM),
    FOREIGN KEY (MECHNUM) REFERENCES MECHANIC(MECHNUM),
    FOREIGN KEY (SKILLNUM) REFERENCES SKILL(SKILLNUM)
    
);


INSERT INTO MECHANIC VALUES('1','Leo','49','300','GREEN');


SELECT AIRNAME FROM AIRPORT
WHERE STATE= 'CALIFORNIA' AND SIZE <= 20 AND YEAROPENED  >= 1953
ORDER BY SIZE DESC;

SELECT AIRNAME FROM AIRPORT
WHERE STATE= 'CALIFORNIA' AND SIZE <= 20 OR YEAROPENED  >= 1953


INSERT INTO MECHANIC VALUES('1','Leo,49,'3000','GREEN');


INSERT INTO MECHANIC VALUES('1','Leo,49,'3000','GREEN');











    
    
